/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React from 'react';

import {createAppContainer} from 'react-navigation';
import {createStackNavigator} from 'react-navigation-stack';

import HomeScreen from './src/HomeScreen'
import ProfileScreen from './src/ProfileScreen'

const MainNavigator = createStackNavigator({
  Home: {screen: HomeScreen},
  ProfileScreen: {screen: ProfileScreen},
})

const App = createAppContainer(MainNavigator)

export default App
